import { mkdir, readFile, writeFile } from 'node:fs/promises'

import dotenv from 'dotenv'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, '..', '..')
const envFile = path.join(projectRoot, '.env.production')

function serializeObject(value, indent = 0) {
  return JSON.stringify(value, null, 2)
    .replace(/"([^"]+)":/g, '$1:')
    .split('\n')
    .map((line, index) => (index === 0 ? line : `${' '.repeat(indent)}${line}`))
    .join('\n')
}

function renderEcosystemConfig({ script, productionEnv }) {
  const envProduction = {
    ...productionEnv,
    NODE_ENV: 'production'
  }
  const logDir = productionEnv.LOG_DIR || 'logs'

  return `// Auto-generated by scripts/deployment/generate_ecosystem.mjs
module.exports = {
  apps: [
    {
      name: 'qxadmin',
      script: '${script}',
      cwd: process.env.PM2_CWD || __dirname,
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      out_file: '${path.posix.join(logDir, 'pm2-out.log')}',
      error_file: '${path.posix.join(logDir, 'pm2-error.log')}',
      merge_logs: true,
      time: true,
      env: ${serializeObject(envProduction, 6)}
    }
  ]
}
`
}

async function loadProductionEnv() {
  const envContent = await readFile(envFile, 'utf8')
  return dotenv.parse(envContent)
}

async function writeEcosystemFile(filePath, content) {
  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, content, 'utf8')
}

async function main() {
  const productionEnv = await loadProductionEnv()

  await writeEcosystemFile(
    path.join(projectRoot, '.output', 'ecosystem.config.js'),
    renderEcosystemConfig({
      script: './server/index.mjs',
      productionEnv
    })
  )

  console.log('Generated .output/ecosystem.config.js')
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
